### ISSUE TITLE
Is this DRY?

### ISSUE THREAD

**Issue by c-myers1** [jan-heise/responsive-navbar-with-dropdown#1]
This is a beautiful navbar but looking at the code, I see the menu is duplicated: over code for the large viewport and one for narrow. When the div containing any one of them is deleted, that corresponding menu doesn’t show up.

Is this not against DRY principles and how can both menus be shown from a single code base?

**Comment by jan-heise** [comment]
I honestly just copied the Markup from https://tailwindui.com BUT you are able to put everything into a single div. 

I will definitely check it out in the coming days.

**Comment by jan-heise** [comment]
As of today this component is not against the DRY principles

**Comment by c-myers1** [comment]
Great!
